### PR TITLE
Remove Ubuntu USG mention

### PR DESCRIPTION
**Pull request by TommyTran732**
No one should stick to Ubuntu LTS just to use Ubuntu Pro on desktop anyways, and the usg stuff is extremely dubious and cause problems.

### CODE REVIEW

**Review by wj25czxj47bu6q — CHANGES_REQUESTED** [review]
I don't think we should remove the mention of Livepatch or Ubuntu LTS in general until we have somewhere else to put the information (Server Linux Hardening?)

**Comment by TommyTran732** [comment]
> I don't think we should remove the mention of Livepatch or Ubuntu LTS in general until we have somewhere else to put the information (Server Linux Hardening?)

Yeah, this post is only for Desktop. We will write a separate server guide later. There is no reason for it to be in this post IMO.

There are other livepatch services for quite cheap too, but we aren't talking about them either, so I don't think theres any reason for the Ubuntu one to be here.

**Comment by wj25czxj47bu6q** [comment]
For better or for worse, some people _do_ run Ubuntu LTS on desktop (especially Linux Mint). Some people are forced to run Ubuntu LTS for software support. Some people also neglect to reboot their computer regularly, instead doing things like putting it in suspend mode all the time.

So I still disagree with the removal of this section. Recommending against Ubuntu LTS is fine, and recommending regular reboots over Livepatch is also fine. But this information should still be kept for those running Ubuntu LTS for one reason or another.

**Comment by TommyTran732** [comment]
> For better or for worse, some people _do_ run Ubuntu LTS on desktop (especially Linux Mint). Some people are forced to run Ubuntu LTS for software support. Some people also neglect to reboot their computer regularly, instead doing things like putting it in suspend mode all the time.
> 
> So I still disagree with the removal of this section. Recommending against Ubuntu LTS is fine, and recommending regular reboots over Livepatch is also fine. But this information should still be kept for those running Ubuntu LTS for one reason or another.

Should we remove the USG stuff or keep it?

Part of it is useful, but some parts are extremely dubious

**Comment by wj25czxj47bu6q** [comment]
Remove. It's much better to identify the specific good changes from USG (ideally in a distro-agnostic way) than to recommend the entire package which is hard to understand and debug.

**Comment by TommyTran732** [comment]
Done

**Pull request merged**
