### PR TITLE
Add workflow for HUGO_VERSION

### PR DESCRIPTION
**Pull request by d4rklynk**
It will update HUGO_VERSION variable in netlify.toml

You obviously still need to check the workflow, I think this one is correct, but I'm not used to github actions.

### CODE REVIEW

**Review by wj25czxj47bu6q — CHANGES_REQUESTED** [review]
Not happy with this.

_Note that I have little familiarity with GitHub Actions in general, so I am erring on the side of extreme caution and trying to avoid assumptions._

- Why is it running daily when Hugo updates are typically multiple weeks apart?
- Why is it running on Ubuntu when Alpine is perfectly sufficient (and would save CI minutes)?
- Why are you using a fragile `grep` and `sed` hack instead of `jq`?
- Why does this automatically commit changes to the repo instead of opening a pull request like Dependabot?
  - To be clear, I have no idea if opening a PR is even possible with GitHub Actions. Either way, automatic committing is unacceptable.
- Use of third&#8209;party Actions makes this workflow opaque and incredibly difficult to audit. Furthermore, it introduces yet another version number with all the usual risks of either updating or not updating.
  - The `write` permission required by the third&#8209;party Action is not shown anywhere in this workflow despite being an incredibly dangerous permission. I sincerely hope GitHub Actions does not implicitly grant it.

This whole thing should ideally be a Dependabot config rather than an Action, but a cursory look at the docs suggests Dependabot cannot do what we need.

See [Renovatebot](https://github.com/renovatebot/renovate) which would be _by far_ the cleanest way to handle this.

**Comment by d4rklynk** [comment]
If we can do it with dependabot, let's do it

**Comment by wj25czxj47bu6q** [comment]
More concerns that have since crossed my mind:

- What happens if the third&#8209;party Action repo is deleted or changes its namespace?
- What happens if the third&#8209;party Action repo remaps its tags?

**Comment by wj25czxj47bu6q** [comment]
> If we can do it with dependabot or renovabot, let's do it

Renovatebot can definitely do it via RegexManager, but we would have to evaluate the trust model of the hosted GitHub App or self-host it. So… not that simple either :upside_down_face:

**Pull request closed without merging**
